### PR TITLE
Updated definition for FRT

### PR DESCRIPTION
**Pull request by aculligan**
Updated definition for FRT and support for Proxima Nova. Changed one translation so buttons would fit
now that the Proxima Nova font size was increased.

@maximeprades could I get a 👍 so this can be merged and sent to the Marketplace? Thanks 😃

### CODE REVIEW

**Comment by maximeprades** [comment]
👍

**Comment by aculligan** [comment]
@maximeprades can this update be pushed to the marketplace? 😃

**Comment by maximeprades** [comment]
@aculligan can't find you on any internal IM tool. you left zendesk?

**Comment by aculligan** [comment]
@maximeprades I did. You can reach me at aculligan@icloud.com

**Comment by maximeprades** [comment]
ah. please update your github profile then and remove Zendesk from it.

Is this App called "SLA Event Tracker" in the marketplace?

**Comment by aculligan** [comment]
Will do. Yes, it is https://www.zendesk.com/apps/sla-event-tracker/

**Comment by maximeprades** [comment]
ok app update. please verify?

**Comment by maximeprades** [comment]
and thx for updating your profile. much appreciated

**Comment by aculligan** [comment]
App is updated.

However, there is a typo on the Overview page in the Marketplace. It says "Allows users to see when SLA metrics where applied, fulfilled, or breached." but it should be "Allows users to see when SLA metrics were applied, fulfilled, or breached.".

The screenshots and banner haven't been updated.

**Comment by maximeprades** [comment]
yea that's on the public marketplace, takes a couple days to update

**Pull request merged**
